spring:
  application:
    name: 'spring security for newbies'


server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
info:
  app:
    name: 'spring security for newbies'

logging:
  level:
    org:
      springframework:
        security:
          authentication: trace
    com:
      example: info


my-secret-value: very-secret
